# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: fast
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code formatting
    - gofmt
    - goimports
    - gci
    - misspell
    - whitespace
    
    # Security (reduced set)
    - gosec
    
    # Code quality (reduced set)
    - dupl
    - unconvert
    - unparam

  settings:
    dupl:
      threshold: 100
    
    funlen:
      lines: 100
      statements: 50
    
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/dsyorkd/pi-controller)
    
    goconst:
      min-len: 3
      min-occurrences: 3
      ignore-tests: true
    
    gocritic:
      settings:
        enabled-tags:
          - diagnostic
          - performance
        disabled-checks:
          - dupImport # https://github.com/go-critic/go-critic/issues/845
          - ifElseChain
          - octalLiteral
          - whyNoLint
          - wrapperFunc
          - hugeParam # Allow large structs to be passed by value for now
          - rangeValCopy # Allow copying in loops for readability  
          - paramTypeCombine # Allow separate parameters for readability
          - stringXbytes # Allow string/byte comparisons
          - unnamedResult # Allow unnamed results
    
    gocyclo:
      min-complexity: 15
    
    goimports:
      local-prefixes: github.com/dsyorkd/pi-controller
    
    govet:
      settings:
        shadow:
          strict: true
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    
    lll:
      line-length: 160  # Increased for long security headers
    
    mnd:
      settings:
        mnd:
          # don't include the "operation" and "assign"
          checks: argument,case,condition,return
    
    misspell:
      locale: US
    
    nolintlint:
      allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped

  exclusions:
    warn-unused: true
    generated: lax
    
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - unparam

      # Allow stub files to be duplicated
      - path: _stub\.go
        linters:
          - dupl

      # Ignore deprecated warnings in test files
      - path: _test\.go
        linters:
          - staticcheck
        text: "SA1019:"
          
      # Allow empty branches in security checks
      - linters:
          - staticcheck
        text: "SA9003:"
          
      # Allow integer overflow conversions in gRPC code for now
      - path: internal/grpc/
        linters:
          - gosec
        text: "G115:"

      # Exclude protobuf generated files
      - path: ".*\\.pb\\.go$"
        linters:
          - all
      
      # Exclude mock files
      - path: ".*_mock\\.go$"
        linters:
          - all
    
    paths:
      - build
      - vendor