// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/pi_controller.proto

package pi_controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
)

// Placeholder - this would normally be generated by protoc
// For Phase 1, we'll use this basic structure

type Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status         ClusterStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=pi_controller.ClusterStatus" json:"status,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	MasterEndpoint string                 `protobuf:"bytes,6,opt,name=master_endpoint,json=masterEndpoint,proto3" json:"master_endpoint,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Nodes          []*Node                `protobuf:"bytes,9,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED   ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_PENDING       ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_PROVISIONING  ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_ACTIVE        ClusterStatus = 3
	ClusterStatus_CLUSTER_STATUS_DEGRADED      ClusterStatus = 4
	ClusterStatus_CLUSTER_STATUS_MAINTENANCE   ClusterStatus = 5
	ClusterStatus_CLUSTER_STATUS_FAILED        ClusterStatus = 6
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress    string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress   string `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Status       NodeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=pi_controller.NodeStatus" json:"status,omitempty"`
	Role         NodeRole `protobuf:"varint,6,opt,name=role,proto3,enum=pi_controller.NodeRole" json:"role,omitempty"`
}

type NodeStatus int32
type NodeRole int32

// Placeholder implementations - this would normally be auto-generated
func (x *Cluster) Reset()         {}
func (x *Cluster) String() string { return "" }
func (*Cluster) ProtoMessage()    {}
func (x *Cluster) ProtoReflect() protoreflect.Message { return nil }

func (x *Node) Reset()         {}
func (x *Node) String() string { return "" }
func (*Node) ProtoMessage()    {}
func (x *Node) ProtoReflect() protoreflect.Message { return nil }

// Descriptor info
var File_proto_pi_controller_proto protoreflect.FileDescriptor

func init() {
	// Placeholder for Phase 1 - would normally be properly generated
	File_proto_pi_controller_proto = nil
}