apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gpiopin-crd.yaml
- pwmcontroller-crd.yaml
- i2cdevice-crd.yaml

commonLabels:
  app.kubernetes.io/name: pi-controller
  app.kubernetes.io/component: crd